spring:
    datasource:
        test-on-borrow: true
        validationQuery: SELECT 1
        driverClassName: com.mysql.jdbc.Driver
#         url: jdbc:mysql://mysqlserver:3306/allenway?useUnicode=true&characterEncoding=UTF-8
        url: jdbc:mysql://localhost:3306/camp?useUnicode=true&characterEncoding=UTF-8
        password: 123456
        username: root

logging.level.root: INFO
logging.level.org.springframework.web: INFO
logging.level.org.hibernate: ERROR
logging.level.com.allenway: DEBUG